#pragma once
#include <iostream>
#include <string>
#include <Windows.h>
#include <Psapi.h>
#include <fileapi.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <chrono>
#include <thread>
#include <ShObjIdl.h>
#include <ShObjIdl_core.h>
#include <ObjIdl.h>
#include <ShlObj.h>
#include <sysinfoapi.h>
#include <VersionHelpers.h>
#include <WinBase.h>

#define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING 
#include <experimental/filesystem>
#pragma warning(disable:4996)